"""add_api_keys_table

Revision ID: 7a6f2063731a
Revises: fde41ad10e32
Create Date: 2026-05-05 23:03:13.166350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6f2063731a'
down_revision: Union[str, Sequence[str], None] = 'fde41ad10e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_client_name', 'api_keys', ['client_name'], unique=False)
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.drop_index(op.f('ix_briefings_niche_generated'), table_name='briefings')
    op.add_column('opportunities', sa.Column('evidence_json', sa.Text(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'evidence_json')
    op.create_index(op.f('ix_briefings_niche_generated'), 'briefings', ['niche_id', 'generated_at'], unique=False)
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_index('ix_api_keys_client_name', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
