"""initial schema

Revision ID: ab8871e14b82
Revises: 
Create Date: 2026-04-22 16:45:30.234228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8871e14b82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('niche_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('briefing_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('trend_velocity', sa.Float(), nullable=False),
    sa.Column('competition_gap', sa.Float(), nullable=False),
    sa.Column('social_signal', sa.Float(), nullable=False),
    sa.Column('monetization_intent', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities')
    op.drop_table('briefings')
    op.drop_table('niches')
    # ### end Alembic commands ###
