"""feat: generalize opportunity domain for propflow and esg

Revision ID: c8159f408a34
Revises: f64b922d9554
Create Date: 2026-05-05 15:29:39.130579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8159f408a34'
down_revision: Union[str, Sequence[str], None] = 'f64b922d9554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('frustration_level', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('opportunities', sa.Column('domain_applicability', sa.String(length=50), server_default='', nullable=False))
    op.add_column('opportunities', sa.Column('domain_reasoning', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'domain_reasoning')
    op.drop_column('opportunities', 'domain_applicability')
    op.drop_column('opportunities', 'frustration_level')
    # ### end Alembic commands ###
