"""add alert_rules table

Revision ID: ecc4a046d932
Revises: c6498feb1d60
Create Date: 2026-05-05 23:23:51.469617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc4a046d932'
down_revision: Union[str, Sequence[str], None] = 'c6498feb1d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('niche_id', sa.String(length=36), nullable=False),
    sa.Column('threshold_score', sa.Float(), nullable=False),
    sa.Column('delivery_channel', sa.String(length=10), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_rules_niche_id_active', 'alert_rules', ['niche_id', 'active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_rules_niche_id_active', table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
