"""add_product_discovery

Revision ID: f64b922d9554
Revises: ab8871e14b82
Create Date: 2026-04-22 19:01:01.901387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64b922d9554'
down_revision: Union[str, Sequence[str], None] = 'ab8871e14b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_briefings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('niche_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('niche_id', sa.String(length=36), nullable=False),
    sa.Column('briefing_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('frustration_level', sa.Float(), nullable=True),
    sa.Column('market_size', sa.Float(), nullable=True),
    sa.Column('competition_gap', sa.Float(), nullable=True),
    sa.Column('willingness_to_pay', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('product_reasoning', sa.Text(), nullable=True),
    sa.Column('recommended_price_range', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['product_briefings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('niches', sa.Column('discovery_mode', sa.String(length=10), server_default='content', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('niches', 'discovery_mode')
    op.drop_table('product_opportunities')
    op.drop_table('product_briefings')
    # ### end Alembic commands ###
